### PR TITLE
 Fix invalid usage of `sinon.sandbox`

### PR DESCRIPTION
**Pull request by ma2ciek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Tests: Fixed invalid usage of `sinon.sandbox`. Closes ckeditor/ckeditor5#1158.

### CODE REVIEW

**Comment by jodator** [comment]
As I was refactoring sandboxes not long ago: wouldn't be better to use  `testUtils.createSinonSandbox()` [from ckeditor5-core](https://github.com/ckeditor/ckeditor5-core/blob/26e91e09d433b9a220f77fe40b82ce229d53a50a/tests/_utils/utils.js#L33-L41) for this?

**Comment by ma2ciek** [comment]
@jodator, on the one hand, I agree, that tests should be consistent. But on the other hand, I don't like the fact, that for simple tests:
 * `testUitls.sinon` adds another complexity to our tests for someone not familiar with the code where the gain is 3-6 lines of declarative code.
 * `testUitls.sinon` should be called `testUitls.sandbox` IMO. 

But it's probably more a content for another issue.

I'll change the code as you suggested.

**Comment by ma2ciek** [comment]
Interestingly it doesn't fail locally. I'll check what's happening on the CI.

**Comment by ma2ciek** [comment]
Closing it, all tests will change soon and I'll have this ticket in my mind.

**Comment by jodator** [comment]
And I've just wanted to start reviewing ;)

**Pull request closed without merging**
